---
title: "Data manipulation"
author: "Zining Qi"
date: "2022-09-22"
output: github_document
---

```{r}
library(tidyverse)

options(tibble.print_min = 3)

litters_data = read_csv("/Users/qizining/Desktop/Data-Wrangling/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("/Users/qizining/Desktop/Data-Wrangling/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)

```

```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)
```

```{r}
select(litters_data, group:gd_of_birth)
```

```{r}
select(litters_data, -pups_survive)
```

```{r}
select(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)
```

```{r}
rename(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)
```

```{r}
select(litters_data, starts_with("gd"))
select(litters_data, ends_with("weight"))
```

```{r}
select(litters_data, litter_number, pups_survive, everything())
```

* `gd_of_birth == 20`
`pups_born_alive >= 2`
`pups_survive != 4`
`!(pups_survive == 4)`
`!((pups_survive == 4) & (gd_of_birth == 20))`
`group %in% c("Con7", "Con8")`
`group == "Con7" & gd_of_birth == 20`


```{r}
filter(litters_data, group == "Con7" & gd_of_birth == 20)
```


```{r}
mutate(litters_data,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```

```{r}
head(arrange(litters_data, group, pups_born_alive), 10)
```

```{r}
head(arrange(litters_data, desc(group), pups_born_alive), 10)
```

```{r}
# Not going to run this!!!
litters_data_raw = read_csv("/Users/qizining/Desktop/Data-Wrangling/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data_clean_names = janitor::clean_names(litters_data_raw)
litters_data_selected_cols = select(litters_data_clean_names, -pups_survive)
litters_data_with_vars = 
  mutate(
    litters_data_selected_cols, 
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group))
litters_data_with_vars_without_missing = 
  drop_na(litters_data_with_vars, wt_gain)
litters_data_with_vars_without_missing
```

```{r}
litters_data_clean = 
  drop_na(
    mutate(
      select(
        janitor::clean_names(
          read_csv("/Users/qizining/Desktop/Data-Wrangling/FAS_litters.csv", col_types = "ccddiiii")
          ), 
      -pups_survive
      ),
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)
    ),
  wt_gain
  )

litters_data_clean
```

```{r}
litters_data = 
  read_csv("/Users/qizining/Desktop/Data-Wrangling/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(wt_gain)

litters_data
```








