---
title: "Data Input"
output: github_document
---

## Data Import: CSVs
```{r}
library(tidyverse)
library(readxl)
library(haven)
```

```{r}
litters_df = read_csv('/Users/qizining/Desktop/Data-Wrangling/FAS_litters.csv')
litters_df = janitor::clean_names(litters_df)
```


Look at the data

```{r}
head(litters_df)
```

```{r, eval=FALSE}
skimr::skim(litters_df)
```


`read_csv` options
```{r, eval=FALSE}
read_csv('/Users/qizining/Desktop/Data-Wrangling/FAS_litters.csv', na = c("", "NA", 999, 88), skip = 2)
```


### Other file formats

We need to read in an excwl sheet

```{r}
mlb_df = read_excel('/Users/qizining/Desktop/Data-Wrangling/mlb11.xlsx')
```

```{r}
lotr_words = read_excel('/Users/qizining/Desktop/Data-Wrangling/LotR_Words.xlsx',
                        range = 'B3:D6')
```

### Read in a SAS dataset.

```{r}
pulse_df = read_sas('/Users/qizining/Desktop/Data-Wrangling/public_pulse_data.sas7bdat')
```

## Data export

```{r}
write_csv(lotr_words, file = '/Users/qizining/Desktop/Data-Wrangling/LotR_Words.csv')
```


## Why not base r???

```{r}
dont_do_this_df = read.csv('/Users/qizining/Desktop/Data-Wrangling/FAS_litters.csv')
```



